x-timezone-env: &timezone-env
  TZ: Asia/Shanghai

services:
  redis:
    image: redis:7-alpine
    container_name: streamtrident-redis
    environment:
      <<: *timezone-env
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --bind
      - 0.0.0.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
