CREATE TABLE IF NOT EXISTS pg_learner (
    id BIGSERIAL PRIMARY KEY,
    session_id VARCHAR(256) NOT NULL,
    learner_name VARCHAR(512) NOT NULL,
    learner_status VARCHAR(16) NOT NULL DEFAULT 'active',
    creation_window_index BIGINT,
    last_seen_window_index BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    current_snapshot_id VARCHAR(128) DEFAULT '',
    current_snapshot_version BIGINT DEFAULT 0,
    flow_count BIGINT NOT NULL DEFAULT 0,
    assignment_share DOUBLE PRECISION,
    unknown_absorb_count BIGINT DEFAULT 0,
    protocol_cluster_type VARCHAR(64),
    temporal_cluster_type VARCHAR(64),
    port_cluster_type VARCHAR(64),
    stability_score DOUBLE PRECISION,
    drift_score DOUBLE PRECISION,
    risk_score DOUBLE PRECISION,
    risk_band VARCHAR(32),
    risk_reason TEXT,
    profile_json JSONB,
    metric_json JSONB,
    rule_json JSONB,
    topology_json JSONB,
    UNIQUE (session_id, learner_name)
);

