"""Shared runtime schema constants.

This module intentionally contains only deployable preprocessing rules. Dataset
sampling, label balancing, topology exports, and other experiment-only logic
should stay outside ``trident_demo.runtime``.
"""

ENVIRONMENT_COLUMNS = {
    "id",
    "Flow ID",
    "Src IP",
    "Dst IP",
    "Src Port",
    "Dst Port",
    "Protocol",
    "Timestamp",
    "Label",
    "Attempted Category",
}

STABLE_STATS_FEATURES = [
    "Flow Duration",
    "Total Fwd Packet",
    "Total Bwd packets",
    "Total Length of Fwd Packet",
    "Total Length of Bwd Packet",
    "Fwd Packet Length Max",
    "Fwd Packet Length Min",
    "Fwd Packet Length Mean",
    "Fwd Packet Length Std",
    "Bwd Packet Length Max",
    "Bwd Packet Length Min",
    "Bwd Packet Length Mean",
    "Bwd Packet Length Std",
    "Flow Bytes/s",
    "Flow Packets/s",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Flow IAT Max",
    "Flow IAT Min",
    "Fwd IAT Total",
    "Fwd IAT Mean",
    "Fwd IAT Std",
    "Fwd IAT Max",
    "Fwd IAT Min",
    "Bwd IAT Total",
    "Bwd IAT Mean",
    "Bwd IAT Std",
    "Bwd IAT Max",
    "Bwd IAT Min",
    "Fwd Header Length",
    "Bwd Header Length",
    "Fwd Packets/s",
    "Bwd Packets/s",
    "Packet Length Min",
    "Packet Length Max",
    "Packet Length Mean",
    "Packet Length Std",
    "Packet Length Variance",
    "FIN Flag Count",
    "SYN Flag Count",
    "RST Flag Count",
    "PSH Flag Count",
    "ACK Flag Count",
    "URG Flag Count",
    "ECE Flag Count",
    "Down/Up Ratio",
    "Average Packet Size",
    "Fwd Segment Size Avg",
    "Bwd Segment Size Avg",
    "Subflow Fwd Packets",
    "Subflow Fwd Bytes",
    "Subflow Bwd Packets",
    "Subflow Bwd Bytes",
    "FWD Init Win Bytes",
    "Bwd Init Win Bytes",
    "fwd_init_win_missing_flag",
    "bwd_init_win_missing_flag",
    "is_non_tcp",
    "flow_bytes_s_missing_flag",
    "Fwd Act Data Pkts",
    "Fwd Seg Size Min",
    "Active Mean",
    "Active Std",
    "Active Max",
    "Active Min",
    "Idle Mean",
    "Idle Std",
    "Idle Max",
    "Idle Min",
]

COMPACT_STATS_FEATURES = [
    "Flow Duration",
    "Total Fwd Packet",
    "Total Bwd packets",
    "Total Length of Fwd Packet",
    "Total Length of Bwd Packet",
    "Fwd Packet Length Mean",
    "Fwd Packet Length Std",
    "Bwd Packet Length Min",
    "Bwd Packet Length Max",
    "Bwd Packet Length Mean",
    "Bwd Packet Length Std",
    "Flow Bytes/s",
    "Flow Packets/s",
    "Flow IAT Mean",
    "Flow IAT Std",
    "Fwd IAT Mean",
    "Fwd IAT Std",
    "Bwd IAT Mean",
    "Bwd IAT Std",
    "Packet Length Mean",
    "Packet Length Std",
    "SYN Flag Count",
    "ACK Flag Count",
    "PSH Flag Count",
    "Average Packet Size",
    "FWD Init Win Bytes",
    "Bwd Header Length",
    "Fwd Bulk Rate Avg",
    "Bwd Bulk Rate Avg",
    "flow_bytes_s_missing_flag",
    "Active Mean",
    "Active Std",
    "Active Max",
    "Idle Mean",
    "Idle Std",
]

TCP_PROTOCOL_NUMBER = 6
FLOW_BYTES_PER_SEC_COLUMN = "Flow Bytes/s"
FLOW_BYTES_PER_SEC_MISSING_FLAG = "flow_bytes_s_missing_flag"
NON_TCP_FLAG_COLUMN = "is_non_tcp"
BENIGN_TYPE_COLUMN = "benign_type"
MISSING_SENTINEL_TO_ZERO_COLUMNS = {
    "FWD Init Win Bytes": "fwd_init_win_missing_flag",
    "Bwd Init Win Bytes": "bwd_init_win_missing_flag",
}
